sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: V89hqcl5SV6AdI+sq6wJCjfAZVNvs1cCyXzGgNPnPp2pJEW9VP1nhWHFIQEmRVadajg1rLDtL46LcTUjA4uGgS4BHV3yDja6gAlPjKnl1gyuxCX2uGRleY/+FbiEmhc8Z09zbUhUqmsJIAgP7MnIecGgFxUaeHhq1Qqei9ZtPMUzSFWpuX2ZNON8Iy3p52Agvr2D4h444s5xvsR6y6I8wb0Ev0olkidxE05LVeTUZmSJ5hOC1Fx33MtKFDIEOnsAnY4GupeKzmq6xilAJnYPJ1WORMGhXyHPlNvKY0LS2OuOPNanXHmfhcos6veIxKzKC7htnmWAhHzic9JV5zRA3VoO4+9pn9tf2eK7LcMXbCjOUpkIfuCultqKyZhvtRlCzFs9RytmH/x3ggIPjtj/BgbFPt3aVeWOSAKsXVwV5V9SEFPZefWODar2I/Gmmz03nXIZDmgtqRGhlsSN8AjWUO/2Ql4qW6NH2LZoAujEoDTBY3v7GyOQu31PdJSmLRsSXc1RMoTTNFycGs/ga8TBk0HfIpWyjwP+7cxduX8+WiF1OP5PDiKd2FfISbDzIO+QUNJLDhgEa8g4iuFKgcfcm+KP3ytNL1BLbRJi3Qj+LI8uvPKDLsCGNUGTRSzdZnor9LJE9CDfyEtuqyMyWW8Hkzw+9PhWhaTe/H69dnoQUl8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Double-Widowing_5193
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy